---
all:
  vars:
    ansible_connection: httpapi
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false

  children:
    arista:
      vars:
        ansible_network_os: arista.eos.eos
        ansible_user: "{{ lookup('env', 'ARISTA_API_USERNAME') }}"
        ansible_password: "{{ lookup('env', 'ARISTA_API_PASSWORD') }}"
      hosts:
        SLEAF01:
          ansible_host: "{{ lookup('env', 'ARISTA_SLEAF01_HOST') }}"
        SLEAF02:
          ansible_host: "{{ lookup('env', 'ARISTA_SLEAF02_HOST') }}"
        SLEAF03:
          ansible_host: "{{ lookup('env', 'ARISTA_SLEAF03_HOST') }}"

    service_leafs:
      hosts:
        SLEAF01:
        SLEAF02:
        SLEAF03:

    fortigate:
      vars:
        ansible_network_os: fortinet.fortios.fortios
      hosts:
        fortigate01:
          ansible_host: "{{ lookup('env', 'FORTIGATE_HOST') }}"
