---
- name: Validate configuration data before deployment
  hosts: localhost
  gather_facts: false

  vars_files:
    - "../group_vars/all.yml"
    - "../group_vars/{{ target_environment | default('test') }}.yml"

  roles:
    - role: validation


- name: Deploy EVPN/VXLAN service leaf configuration to Arista
  hosts: service_leafs
  gather_facts: false
  connection: httpapi

  vars_files:
    - "../group_vars/all.yml"
    - "../group_vars/{{ target_environment | default('test') }}.yml"

  roles:
    - role: spine_leaf
      when: datacenter_network.enabled | default(true)


- name: Deploy network security configuration to FortiGate
  hosts: fortigate
  gather_facts: false
  connection: httpapi

  vars_files:
    - "../group_vars/all.yml"
    - "../group_vars/{{ target_environment | default('test') }}.yml"

  vars:
    fortigate_access_token: "{{ lookup('env', 'FORTIGATE_API_TOKEN') }}"
    fortigate_vdom: "{{ network_security_stack.fortigate.vdom | default('root') }}"

  roles:
    - role: fortigate
      when: network_security_stack.fortigate.enabled | default(true)
