- name: Configure FortiGate address objects
  fortinet.fortios.fortios_firewall_address:
    access_token: "{{ lookup('env', 'FORTIGATE_API_TOKEN') }}"
    vdom: "root"
    state: present
    firewall_address:
      name: "ADDR_{{ item.name | upper }}_NET"
      subnet: "{{ item.subnet | ansible.utils.ipaddr('network') }} {{ item.subnet | ansible.utils.ipaddr('netmask') }}"
      type: ipmask
  loop: "{{ network_security_stack.zones }}"
  vars:
    ansible_connection: httpapi
    ansible_network_os: fortinet.fortios.fortios
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
  delegate_to: fortigate01